protected_pages.settings:
  type: config_object
  label: 'Settings'
  mapping:
    password:
      type: config_object
      mapping:
        per_page_or_global:
          type: string
          label: 'Global Password Setting'
        global_password:
          type: config_object
          label: 'Global Password'
          mapping:
            pass1:
              type: string
              label: 'Password'
            pass2:
              type: string
              label: 'Confirm Password'
        protected_pages_session_expire_time:
          type: string
          label: 'Session Expire Time'
    email:
      type: config_object
      mapping:
        subject:
          type: string
          label: 'Email subject'
        body:
          type: string
          label: 'Email content'
    others:
      type: config_object
      mapping:
        protected_pages_title:
          type: string
          label: 'Protected Page -- Enter password'
        protected_pages_description:
          type: string
          label: 'The page you are trying to view is password protected. Please enter the password below to proceed.'
        protected_pages_password_label:
          type: string
          label: 'Enter Password'
        protected_pages_submit_button_text:
          type: string
          label: 'Authenticate'
        protected_pages_incorrect_password_msg:
          type: string
          label: 'Incorrect password!'
    langcode:
      type: string
      label: 'Language code'
